<?php

// <DDSETTINGS>
// Please don't edit anything between <DDSETTINGS> tags.
// This section is autogenerated by Acquia Dev Desktop.
if (isset($_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR']) && file_exists($_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR'] . '/loc_drupal_assigntest_dd.inc')) {
  require $_SERVER['DEVDESKTOP_DRUPAL_SETTINGS_DIR'] . '/loc_drupal_assigntest_dd.inc';
}
// </DDSETTINGS>

$settings['hash_salt']  = "drupal9test";
$databases = array (
  'default' =>
  array (
    'default' =>
    array (
      'database' => 'drupal-assign-test',
      'username' => 'root',
      'password' => '',
      'host' => 'localhost',
      'driver' => 'mysql',
      'prefix' => '',
      'port'   => 33067
    ),
  ),
);

//temporary files
$settings["file_temp_path"] = 'tmp';


//Error reporting
$config['system.logging']['error_level'] = 'verbose';

//Disable local caches
$settings['container_yamls'][] = DRUPAL_ROOT . '/sites/development.services.local.yml';
$settings['cache']['bins']['render'] = 'cache.backend.null';
$settings['cache']['bins']['dynamic_page_cache'] = 'cache.backend.null';
$settings['cache']['bins']['bootstrap'] = 'cache.backend.memory';
$settings['cache']['bins']['discovery'] = 'cache.backend.database';
$settings['cache']['bins']['config'] = 'cache.backend.database';
$settings['cache']['default'] = 'cache.backend.database';


// Theming debug
$config['system.performance']['css']['preprocess'] = FALSE;
$config['system.performance']['js']['preprocess'] = FALSE;
$settings['twig_debug'] = TRUE;


//Limit nesting of devel
//require_once DRUPAL_ROOT . '/modules/contrib/devel/kint/kint/Kint.class.php';
//Kint::$maxLevels = 3;
