<?php

/**
 * @file
 * The administration module.
 */


use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\Request;
use Drupal\Core\Cache\Cache;
use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function administration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the administration module.
    case 'help.page.administration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Administration') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function administration_theme() {
  return [
    'date_display_service_block' => [
      'variables' => [
        'block_data' => NULL,
        'service_data' => NULL,
        'time_zone' => NULL
      ],
      'template' => 'block--date-display-service',
    ],
  ];
}
